"""Categories -> Document Types; Extractions -> FieldValue tree.

Hand-written (not autogenerated) so existing rows survive: autogenerate would
emit drop+create and throw away documents, OCR output, chunks and embeddings.
Every step is guarded, so this is safe on a fresh database created by
`init-db` (already new shape) as well as on an existing one.

Revision ID: 0001_doctypes
Revises:
Create Date: 2026-07-28
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_doctypes"
down_revision = None
branch_labels = None
depends_on = None


def _has_table(conn, name: str) -> bool:
    return sa.inspect(conn).has_table(name)


def _has_column(conn, table: str, column: str) -> bool:
    if not _has_table(conn, table):
        return False
    return any(c["name"] == column for c in sa.inspect(conn).get_columns(table))


def upgrade() -> None:
    conn = op.get_bind()

    # ---------------------------------------------------------------- renames
    renames = [
        ("categories", "document_types"),
        ("extraction_schemas", "type_schemas"),
        ("extractions", "field_values"),
        ("document_category", "document_type_links"),
        ("category_default_permissions", "document_type_default_permissions"),
    ]
    for old, new in renames:
        if _has_table(conn, old) and not _has_table(conn, new):
            op.rename_table(old, new)

    # category_id -> document_type_id everywhere it survived the table rename
    for table in ("type_schemas", "field_values", "classifications",
                  "document_type_links", "document_type_default_permissions"):
        if _has_column(conn, table, "category_id"):
            op.alter_column(table, "category_id", new_column_name="document_type_id")

    if _has_column(conn, "review_items", "extraction_id"):
        op.alter_column("review_items", "extraction_id", new_column_name="field_value_id")

    # ------------------------------------------------- new field_values shape
    if _has_table(conn, "field_values"):
        add = [
            ("parent_id", sa.Column("parent_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True)),
            ("field_key", sa.Column("field_key", sa.String(128), nullable=True)),
            ("field_path", sa.Column("field_path", sa.String(512), nullable=True)),
            ("node_kind", sa.Column("node_kind", sa.String(16), nullable=False, server_default="scalar")),
            ("ordinal", sa.Column("ordinal", sa.Integer(), nullable=True)),
            ("data_type", sa.Column("data_type", sa.String(16), nullable=False, server_default="text")),
            ("value_datetime", sa.Column("value_datetime", sa.DateTime(timezone=True), nullable=True)),
            ("value_time", sa.Column("value_time", sa.Time(), nullable=True)),
            ("value_boolean", sa.Column("value_boolean", sa.Boolean(), nullable=True)),
            ("is_discovered", sa.Column("is_discovered", sa.Boolean(), nullable=False, server_default=sa.false())),
        ]
        for name, col in add:
            if not _has_column(conn, "field_values", name):
                op.add_column("field_values", col)

        # Backfill: existing flat rows become depth-1 scalar leaves.
        conn.execute(sa.text("""
            UPDATE field_values
               SET field_key = COALESCE(field_key,
                       regexp_replace(lower(trim(field_name)), '[^a-z0-9]+', '_', 'g')),
                   data_type = COALESCE(NULLIF(data_type, 'text'), value_type, 'string'),
                   node_kind = COALESCE(node_kind, 'scalar')
             WHERE field_key IS NULL OR data_type IS NULL
        """))
        conn.execute(sa.text(
            "UPDATE field_values SET field_path = field_key WHERE field_path IS NULL"))

        op.alter_column("field_values", "field_key", nullable=False)
        op.alter_column("field_values", "field_path", nullable=False)

        op.create_foreign_key("fk_field_values_parent", "field_values", "field_values",
                              ["parent_id"], ["id"], ondelete="CASCADE")
        op.create_index("ix_field_values_parent_id", "field_values", ["parent_id"])
        op.create_index("ix_field_values_key", "field_values", ["tenant_id", "field_key"])
        op.create_index("ix_field_values_path", "field_values", ["field_path"])
        op.create_unique_constraint("uq_field_value_path", "field_values",
                                    ["document_id", "document_version", "field_path"])

    # ------------------------------------------------------- document changes
    if not _has_column(conn, "documents", "duplicate_of_id"):
        op.add_column("documents", sa.Column(
            "duplicate_of_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True))
        op.create_foreign_key("fk_documents_duplicate_of", "documents", "documents",
                              ["duplicate_of_id"], ["id"], ondelete="SET NULL")
    if not _has_column(conn, "documents", "requested_type_id"):
        op.add_column("documents", sa.Column(
            "requested_type_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True))
        op.create_foreign_key("fk_documents_requested_type", "documents", "document_types",
                              ["requested_type_id"], ["id"], ondelete="SET NULL")

    if not _has_column(conn, "document_types", "is_system"):
        op.add_column("document_types", sa.Column(
            "is_system", sa.Boolean(), nullable=False, server_default=sa.false()))
        conn.execute(sa.text(
            "UPDATE document_types SET is_system = true WHERE name IN ('Contracts','Invoices')"))
    if not _has_column(conn, "type_schemas", "created_by"):
        op.add_column("type_schemas", sa.Column(
            "created_by", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True))

    # Existing flat schemas: give every field a stable key and a data_type the
    # new validator understands (they were {name, type, description}).
    conn.execute(sa.text("""
        UPDATE type_schemas ts
           SET fields = sub.converted
          FROM (
            SELECT t.id,
                   jsonb_agg(jsonb_build_object(
                     'key', regexp_replace(lower(trim(f->>'name')), '[^a-z0-9]+', '_', 'g'),
                     'name', f->>'name',
                     'description', COALESCE(f->>'description', ''),
                     'data_type', CASE COALESCE(f->>'type', 'text')
                                    WHEN 'text' THEN 'string'
                                    WHEN 'numeric' THEN 'number'
                                    ELSE COALESCE(f->>'type', 'string') END,
                     'required', false
                   ) ORDER BY ord) AS converted
              FROM type_schemas t,
                   LATERAL jsonb_array_elements(t.fields) WITH ORDINALITY AS a(f, ord)
             WHERE jsonb_typeof(t.fields) = 'array'
               AND NOT (f ? 'key')
             GROUP BY t.id
          ) sub
         WHERE ts.id = sub.id
    """))

    # Document names must be unique per tenant among live documents. De-duplicate
    # any existing collisions first so the index can be created.
    conn.execute(sa.text("""
        UPDATE documents d
           SET name = d.name || ' (' || d2.seq || ')'
          FROM (
            SELECT id,
                   row_number() OVER (PARTITION BY tenant_id, name ORDER BY created_at) AS seq
              FROM documents WHERE is_deleted = false
          ) d2
         WHERE d.id = d2.id AND d2.seq > 1
    """))
    op.create_index("uq_document_tenant_name_live", "documents", ["tenant_id", "name"],
                    unique=True, postgresql_where=sa.text("is_deleted = false"))


def downgrade() -> None:
    conn = op.get_bind()
    op.drop_index("uq_document_tenant_name_live", table_name="documents")
    for name in ("uq_field_value_path",):
        op.drop_constraint(name, "field_values", type_="unique")
    for name in ("ix_field_values_path", "ix_field_values_key", "ix_field_values_parent_id"):
        op.drop_index(name, table_name="field_values")
    op.drop_constraint("fk_field_values_parent", "field_values", type_="foreignkey")
    for col in ("parent_id", "field_key", "field_path", "node_kind", "ordinal", "data_type",
                "value_datetime", "value_time", "value_boolean", "is_discovered"):
        if _has_column(conn, "field_values", col):
            op.drop_column("field_values", col)
    op.drop_column("documents", "duplicate_of_id")
    op.drop_column("documents", "requested_type_id")
    op.drop_column("document_types", "is_system")
    op.drop_column("type_schemas", "created_by")
    if _has_column(conn, "review_items", "field_value_id"):
        op.alter_column("review_items", "field_value_id", new_column_name="extraction_id")
    for table in ("type_schemas", "field_values", "classifications",
                  "document_type_links", "document_type_default_permissions"):
        if _has_column(conn, table, "document_type_id"):
            op.alter_column(table, "document_type_id", new_column_name="category_id")
    for new, old in [
        ("document_types", "categories"),
        ("type_schemas", "extraction_schemas"),
        ("field_values", "extractions"),
        ("document_type_links", "document_category"),
        ("document_type_default_permissions", "category_default_permissions"),
    ]:
        if _has_table(conn, new) and not _has_table(conn, old):
            op.rename_table(new, old)
